export const ROUTES = {
  adminCredentials: '/admin/credenciales',
  adminRegisterUniversity: '/admin/universidades/registrar',
  adminRoot: '/admin',
  adminUniversities: '/admin/universidades',
  firstLoginPassword: '/primer-ingreso/cambiar-contrasena',
  forgotPassword: '/recuperar-contrasena',
  home: '/',
  login: '/login',
  patientAppointments: '/paciente/citas',
  patientConversations: '/paciente/conversaciones',
  patientProfile: '/paciente/mi-perfil',
  patientRequests: '/paciente/solicitudes',
  patientRoot: '/paciente',
  patientSearchStudents: '/paciente/buscar-estudiantes',
  register: '/registro',
  studentAgenda: '/estudiante/agenda',
  studentConversations: '/estudiante/conversaciones',
  studentProfile: '/estudiante/mi-perfil',
  studentRequests: '/estudiante/solicitudes',
  studentRoot: '/estudiante',
  studentTreatments: '/estudiante/tratamientos-y-sedes',
  universityBulkUpload: '/universidad/carga-masiva',
  universityCredentials: '/universidad/credenciales',
  universityInstitution: '/universidad/informacion-institucional',
  universityRegisterStudent: '/universidad/estudiantes/registrar',
  universityRegisterTeacher: '/universidad/docentes/registrar',
  universityRoot: '/universidad',
  universityStudents: '/universidad/estudiantes',
  universityTeachers: '/universidad/docentes',
  verifyEmail: '/verificar-correo',
} as const;

export type AppRoute = (typeof ROUTES)[keyof typeof ROUTES];
